server:
  port: 8080
spring:
  application:
    name: "AuthService"
  devtools:
    add-properties: false
adapters:
  r2dbc:
    host: ${DB_HOST:localhost}
    port: ${DB_PORT:5432}
    scheme: ${DB_SCHEME:public}
    database: ${DB_NAME:authdb}
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:pass}
  profiles:
    include: null
token:
  jwt:
    secret: ${JWT_SECRET:miClaveSuperSegura123!@#abcDEF456$%^789ExtraLargaConMuchosChars987654321}
    expiration: ${JWT_EXPIRATION:3600000}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
